name: Auto Merge on Label

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Auto Merge'
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (pr.state === 'open' && pr.mergeable_state === 'clean') {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log('PR merged!');
            } else {
              console.log('PR not mergeable');
            }
